title: Flávio Website
email: 97ferreira.flavio@gmail.com
description: >-
  Portfolio website for Flávio Ferreira, a portuguese developer
  who grew up playing video games and now enjoys programming
  fun, interesting and useful projects.
#url: "" # the base hostname & protocol for your site, e.g. http://example.com
#twitter_username: jekyllrb
github_username:  LDKid
permalink: pretty


# Define the default language and the list of languages.
lang: en
languages: ["en", "pt"]

# Define the creators of the website.
programmer: Flávio Ferreira
designer: João Rodrigo

# Setup defaults, this handles the paths and languages
defaults:
  - 
    scope:
      path: ""
    values:
      lang: "en"
  - 
    scope:
      path: "pt"
    values:
      lang: "pt"
  -
    scope:
      path: "_projects/en"
    values:
      permalink: "/en/portfolio/:title"
      lang: "en"
      layout: "project"
      cover: "cover.png"
      cover-pixel: "cover64.png"
      icon: "icon.png"
  -
    scope:
      path: "_projects/pt"
    values:
      permalink: "/pt/portfolio/:title"
      lang: "pt"
      layout: "project"
      cover: "cover.png"
      cover-pixel: "cover64.png"
      icon: "icon.png"
  -
    scope:
      path: "_about/en"
    values:
      lang: "en"
  -
    scope:
      path: "_about/pt"
    values:
      lang: "pt"

# Setup collections
collections:
  projects:
    sort_by: date
    output: true
  about:
    sort_by: date
    output: false

# Build settings
plugins:
  - jekyll-feed
  - jekyll-redirect-from
whitelist:
  - jekyll-redirect-from

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
